### ISSUE TITLE
When running MORGEN.jar with option -v, time should be given in seconds

### ISSUE THREAD

**Issue by steinbeck** [MehmetAzizYirik/AlgorithmicGroupTheory#15]
When running MORGEN.jar with option -v, time should be given in seconds.
Seems like a minor detail, but important.

```
java -jar MORGEN.jar -f C10H16 -v
MORGEN is generating isomers of C10H16...
The number of structures is: 24938
Time: 2.277

```
should be "Time: 2.277 seconds"

**Comment by MehmetAzizYirik** [comment]
Thanks. I changed it and will push the updated version of the class.
