### ISSUE TITLE
Option -D should be replaced with -o and take a filename (plus optional path) as argument.

### ISSUE THREAD

**Issue by steinbeck** [MehmetAzizYirik/AlgorithmicGroupTheory#17]
Option -D should be replaced with -o and take a filename (plus optional path) as an argument.
Furthermore, it is important that "maygen.jar -o -" writes output to standard out (use "System.out" as filename). 

Like: BufferedWriter log = new BufferedWriter(new OutputStreamWriter(System.out));

This means that the option "-o" just gets the hyphen as an argument. This is a general convention in Unix and allows one to do things like "java -jar maygen.jar -o - | gzip > mycalc.sdf.gz" when one expects many solutions and a large SDF. This command compresses the SDF on the fly and allows the generation of very large SDF files with small hard disk footprint. 

With the current version, I cannot generate the isomers of C15H24 on a google machine with 10GB Harddisk space.

**Comment by javadev** [comment]
@MehmetAzizYirik Code changes was added https://github.com/MehmetAzizYirik/AlgorithmicGroupTheory/pull/20

**Comment by javadev** [comment]
@steinbeck The new option -o was added. This code should work from now:

```
java -jar maygen.jar -f C5N3H9 -v -o - | gzip > mycalc.sdf.gz
```
